### PR TITLE
Enable config ServiceInstance weight and provide WeightedLoadBalancer

### PR DESCRIPTION
**Pull request by jizhuozhi**
#1102

### CODE REVIEW

**Comment by jizhuozhi** [comment]
As said in the issue, the **EDF(Earliest Deadline First) algorithm with PriorityQueue** needs to maintain additional data structures, and the distribution obtained by the **Random Binary Search algorithm** does not meet the expectations of the weight distribution, I chose the one **EDF(Earliest Deadline First) algorithm without PriorityQueue** to implement the **weighted-loadbalancing strategy**.

In order to see the performance overhead more intuitively, I used JMH to perform microbenchmark. From the results, we can see that there is no obvious performance difference in the order of 1-1000, and there is a 50% performance difference in the order of 10,000.

This is not in line with the linear growth trend obtained by the O(n), which means that we have done a lot of functions with higher performance overhead than the load balancing algorithm, so the impact of the choice of the load balancing algorithm is negligible.

```
# JMH version: 1.35
# VM version: JDK 17, OpenJDK 64-Bit Server VM, 17+35-2724
# CPU: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
Benchmark                                                (hostCount)   Mode  Cnt      Score       Error  Units
LoadBalancerBenchmarkTests.roundRobinLoadBalancerChoose            1  thrpt    5  35139.376 ±  8227.186  ops/s
LoadBalancerBenchmarkTests.roundRobinLoadBalancerChoose           10  thrpt    5  36126.110 ±  9791.313  ops/s
LoadBalancerBenchmarkTests.roundRobinLoadBalancerChoose          100  thrpt    5  36052.640 ±  7074.979  ops/s
LoadBalancerBenchmarkTests.roundRobinLoadBalancerChoose         1000  thrpt    5  35673.049 ±  7444.958  ops/s
LoadBalancerBenchmarkTests.roundRobinLoadBalancerChoose        10000  thrpt    5  35959.145 ±  8168.653  ops/s
LoadBalancerBenchmarkTests.weightedLoadBalancerChoose              1  thrpt    5  36069.203 ±  6864.469  ops/s
LoadBalancerBenchmarkTests.weightedLoadBalancerChoose             10  thrpt    5  34009.018 ± 17003.501  ops/s
LoadBalancerBenchmarkTests.weightedLoadBalancerChoose            100  thrpt    5  33240.746 ± 14310.607  ops/s
LoadBalancerBenchmarkTests.weightedLoadBalancerChoose           1000  thrpt    5  32507.614 ±  4630.958  ops/s
LoadBalancerBenchmarkTests.weightedLoadBalancerChoose          10000  thrpt    5  20108.035 ±  2929.412  ops/s
```
Finally I chose **EDF(Earliest Deadline First) algorithm without PriorityQueue** as my solution

**Comment by jizhuozhi** [comment]
@OlgaMaciaszek  Hello, PTAL.

**Comment by jizhuozhi** [comment]
Adding concurrently benchmark report
```
LoadBalancerBenchmarkTests.roundRobinLoadBalancerChooseConcurrently            1  thrpt    5  31545.422 ± 2151.797  ops/s
LoadBalancerBenchmarkTests.roundRobinLoadBalancerChooseConcurrently           10  thrpt    5  31604.939 ± 2337.547  ops/s
LoadBalancerBenchmarkTests.roundRobinLoadBalancerChooseConcurrently          100  thrpt    5  31444.068 ± 2233.952  ops/s
LoadBalancerBenchmarkTests.roundRobinLoadBalancerChooseConcurrently         1000  thrpt    5  31659.013 ± 2228.136  ops/s
LoadBalancerBenchmarkTests.weightedLoadBalancerChooseConcurrently              1  thrpt    5  31451.775 ± 2269.753  ops/s
LoadBalancerBenchmarkTests.weightedLoadBalancerChooseConcurrently             10  thrpt    5  31432.169 ± 2177.994  ops/s
LoadBalancerBenchmarkTests.weightedLoadBalancerChooseConcurrently            100  thrpt    5  31463.261 ± 2294.697  ops/s
LoadBalancerBenchmarkTests.weightedLoadBalancerChooseConcurrently           1000  thrpt    5  30369.156 ± 2672.340  ops/s
```

**Comment by jizhuozhi** [comment]
@OlgaMaciaszek Hello, I modified the ServiceInstance interface to make it stateful for recording the weight and current weight, also provide a WeightedLoadBalancer which was thread-safe with tests, PTAL

**Comment by OlgaMaciaszek** [comment]
Hello @jizhuozhi - thanks a lot for submitting the PR. I will go through it next week. However, since it's a major new feature and not a bugfix, please submit this PR against `main` instead of `3.1.x`.

**Comment by OlgaMaciaszek** [comment]
Closing in favour of https://github.com/spring-cloud/spring-cloud-commons/pull/1111.

**Pull request closed without merging**
