### PR TITLE
RestartEndpoint fixed

### PR DESCRIPTION
**Pull request by plajko**
Previous implementation did the same. Current is only stopping the instance for me, fails to start it again. With this fix it is working as expected.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@plajko Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-commons&pullRequestId=366)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-commons&pullRequestId=366) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@plajko Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-commons&pullRequestId=366)!

**Comment by ryanjbaxter** [comment]
> Previous implementation did the same

Can you elaborate?

**Comment by plajko** [comment]
I mean this one:
https://github.com/spring-cloud/spring-cloud-commons/blob/1.3.x/spring-cloud-context/src/main/java/org/springframework/cloud/context/restart/RestartMvcEndpoint.java

Http post request to restart endpoint called the method on a separate thread in 1.3.x. (Spring Boot 1.x style endpoint implementation)

**Pull request merged**
