### PR TITLE
Ensure that the bootstrap context is closed after refresh.

### PR DESCRIPTION
**Pull request by spencergibb**
see https://github.com/spring-cloud/spring-cloud-zookeeper/issues/123

### CODE REVIEW

**Comment by spencergibb** [comment]
@dsyer I know this is a bit of a hack, but it works. Any suggestions on how it could be done better? Should be included in Edgware.

**Comment by dsyer** [comment]
I think this would be better:

```
diff --git a/spring-cloud-context/src/main/java/org/springframework/cloud/context/refresh/ContextRefresher.java b/spring-cloud-context/src/main/java/org/springframework/cloud/context/refresh/ContextRefresher.java
index c57a25b..e4979db 100644
--- a/spring-cloud-context/src/main/java/org/springframework/cloud/context/refresh/ContextRefresher.java
+++ b/spring-cloud-context/src/main/java/org/springframework/cloud/context/refresh/ContextRefresher.java
@@ -102,7 +102,20 @@ public class ContextRefresher {
                }
                finally {
                        ConfigurableApplicationContext closeable = capture;
-                       closeable.close();
+                       while (closeable != null) {
+                               try {
+                                       closeable.close();
+                               }
+                               catch (Exception e) {
+                                       // Ignore;
+                               }
+                               if (closeable.getParent() instanceof ConfigurableApplicationContext) {
+                                       closeable = (ConfigurableApplicationContext) closeable.getParent();
+                               }
+                               else {
+                                       break;
+                               }
+                       }
                }
 
        }
```

**Comment by spencergibb** [comment]
Closed via abe5374c792094826bc7c96d36d44473757f4c91

**Comment by zachmarshall** [comment]
I think this fixes #211 right?

**Pull request closed without merging**
