### PR TITLE
Use newCachedTreadPool() instead of newSingleThreadExecutor() in InetUtils

### PR DESCRIPTION
**Pull request by stsypanov**
See https://github.com/spring-cloud/spring-cloud-commons/issues/1364

### CODE REVIEW

**Comment by OlgaMaciaszek** [comment]
Fixes gh-1364.

**Review by OlgaMaciaszek — CHANGES_REQUESTED** [review]
Hi @stsypanov. Thanks for adding the PR. However, could you please submit the change against the `4.1.x` branch instead? Also, please add your full name and last name with the `@author` tag to the class Javadoc and update the date in the license comment to `2012-2024`

**Comment by stsypanov** [comment]
@OlgaMaciaszek done!

**Review by OlgaMaciaszek — APPROVED** [review]
Thanks @stsypanov. LGTM.

**Pull request merged**
