### PR TITLE
Fix #132: Implemented proper synchronization of executorService in InetUtils

### LINKED ISSUE #132: RejectedExecutionException in InetUtils while running multiple spring-boot instances
While running multiple instances of spring boot simultaneously (for testing purposes), sometimes, I can see the following error:
````
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@4ab3fe1e rejected from java.util.concurrent.ThreadPoolExecutor@37bb0571[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047)
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369)
        at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
        at java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:681)
        at org.springframework.cloud.commons.util.InetUtils.convertAddress(InetUtils.java:142)
        at org.springframework.cloud.commons.util.InetUtils.findFirstNonLoopbackHostInfo(InetUtils.java:71)
        at org.springframework.cloud.client.HostInfoEnvironmentPostProcessor.getFirstNonLoopbackHostInfo(HostInfoEnvironmentPostProcessor.java:49)
        at org.springframework.cloud.client.HostInfoEnvironmentPostProcessor.postProcessEnvironment(HostInfoEnvironmentPostProcessor.java:34)
        at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEnvironmentPreparedEvent(ConfigFileApplicationListener.java:168)
        at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEvent(ConfigFileApplicationListener.java:154)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:166)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:121)
        at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:68)
        at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
        at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:335)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
        at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134)
        at org.springframework.cloud.bootstrap.BootstrapApplicationListener.bootstrapServiceContext(BootstrapApplicationListener.java:140)
        at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:84)
        at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:1)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:166)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:121)
        at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:68)
        at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
        at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:335)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
        at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134)

````
Evidently, the problem is wrong synchronization of `executorService` in `InetUtils`. So, after one thread has called `getExecutor()`, another has called `close()` method. Then, first thread tries to submit a new job to a shutted down `ExecutorService`

### PR DESCRIPTION
**Pull request by pbaranchikov**
As `executorService` could be shut down from another thread, it is not suficient to synchronize its lazy initialization, but it is also required to synchronized its usage in order to prevent another thread from shutting down the `executorService` right before its usage.

As fix is thread-safety oriented, there is not tests intoduced to cover the case.

fixes #132

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@pbaranchikov Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-commons&pullRequestId=133)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-commons&pullRequestId=133) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@pbaranchikov Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-commons&pullRequestId=133)!

**Comment by spencergibb** [comment]
I'm not keen on an optimization for something that isn't really supported.
> While running multiple instances of spring boot simultaneously (for testing purposes), sometimes, I can see the following error:

Thoughts @dsyer or @ryanjbaxter?

**Comment by pbaranchikov** [comment]
@spencergibb , the change fixes the error in thread safety. I do not know other scenarios, that could cause creation of multiple instances of InetUtils. If there are the scenarios they can also cause the error reported.

If you are not supporting creation of multiple instances of InetUtils, why does the class use static member executorService? Why introduce any static variable, that is used locally from instance, if you are not expecting multiple instances? This leads me to the conclusion, that by design InetUtils expect multiple instances to be created.

**Comment by pbaranchikov** [comment]
@spencergibb I agree with you approach to make executorService non-static. Please take a look at new version of PR.

**Pull request merged**
