### PR TITLE
actuate endpoint "actuator/serviceregistry" return object type error

### PR DESCRIPTION
**Pull request by guerlab**
fixed https://github.com/spring-cloud/spring-cloud-commons/issues/1051#issue-1075710606

### CODE REVIEW

**Review by spencergibb — CHANGES_REQUESTED** [review]
we use tabs, not spaces

**Comment by guerlab** [comment]
> we use tabs, not spaces

i fixed code style

**Review by guerlab — COMMENTED** [review]
i fixed code style

**Comment by spencergibb** [comment]
cherry picked to 3.0.x

**Pull request merged**
