### PR TITLE
Skips docker's interfaces

### PR DESCRIPTION
**Pull request by zanella**
The valid IP can be used for communicating w/ docker and w/ the outside, which is probably what you want when developing

### CODE REVIEW

**Comment by spencergibb** [comment]
@dsyer @adriancole @marcingrzejszczak This pains me that I wrote this as a static method. I'd like to make the interfaces to skip configurable. Should I add a parameter that takes a configuration properties object, or move this to a bean? As I type the question, the answer seems to me to move it to a bean if I'm going to make it configurable.

**Comment by dsyer** [comment]
Yep. It's not too late for 1.1.0. The ship has sailed on Brixton.M4 I think (so please don't change the architecture in anything that depends on commons till after that).

**Comment by spencergibb** [comment]
@dsyer will do.

**Comment by spencergibb** [comment]
Closing in favor of #75. Thanks for getting the ball rolling on this.

**Comment by pcornelissen** [comment]
So this won't go into Brixton at all?

**Pull request closed without merging**
