### PR TITLE
Fix GenericScope so that multiple subclasses can live in the same con…

### PR DESCRIPTION
**Pull request by mbenson**
…text (non-static inner class cannot resolve parent bean)

### CODE REVIEW

**Comment by spencergibb** [comment]
@dsyer thoughts?

**Comment by dsyer** [comment]
LGTM. Why is the lock method package private though?

**Comment by mbenson** [comment]
`private` didn't seem to be accessible to the inner class. I will double-check.

**Comment by mbenson** [comment]
If accepted, I will also submit a PR to merge the commit to `master`.

**Comment by spencergibb** [comment]
No need, we merge forward

**Comment by mbenson** [comment]
My point was that there are conflicts which I was offering to resolve. ;) But either way, they're not significant.

**Comment by spencergibb** [comment]
Closed via 3f9315dca1cde4720275d9768f883f60151bd792

**Pull request closed without merging**
