### PR TITLE
fix bug of XForwardedHeadersTransformer ConditionalOnBean

### PR DESCRIPTION
**Pull request by galaxy-sea**
Should use `@ConditionalOnBean(LoadBalancerClientFactory.class)` on `xForwarderHeadersTransformer` method, not `@ConditionalOnBean({ XForwardedHeadersTransformer.class, LoadBalancerClientFactory.class })`

### CODE REVIEW

**Review by OlgaMaciaszek — APPROVED** [review]
Hello @galaxy-sea , thanks for submitting the PR. Looks like a  bug, quite unexpected that it was not reported  earlier. Thanks for the fix.

**Comment by OlgaMaciaszek** [comment]
Merged within 5f32ef216fef88f0b768a2394e7c60cc63960e39.

**Comment by OlgaMaciaszek** [comment]
Hello, @galaxy-sea , on a second thought, I think that might have been added on purpose so that users can extend the class and instantiate as a bean instead of the one provided by us. Reverting the change.

**Comment by galaxy-sea** [comment]
hello  @OlgaMaciaszek 

# reactive

But this is a bug. The XForwardedHeadersTransformer does not load by default. It requires me to provide an XForwardedHeadersTransformer bean to load, Two XForwardedHeadersTransformer beans with the same function are unnecessary

``org.springframework.cloud.loadbalancer.annotation.LoadBalancerClientConfiguration.ReactiveSupportConfiguration``
```java
    // org.springframework.cloud.loadbalancer.core.XForwardedHeadersTransformer
    @Bean
    @ConditionalOnBean({ XForwardedHeadersTransformer.class, LoadBalancerClientFactory.class })
    @ConditionalOnMissingBean
    public XForwardedHeadersTransformer xForwarderHeadersTransformer(LoadBalancerClientFactory clientFactory) {
        return new XForwardedHeadersTransformer(clientFactory);
    }
```
# servlet

``org.springframework.cloud.loadbalancer.config.BlockingLoadBalancerClientAutoConfiguration``
```java
    // org.springframework.cloud.loadbalancer.blocking.XForwardedHeadersTransformer
	@Bean
	@ConditionalOnMissingBean(XForwardedHeadersTransformer.class)
	@ConditionalOnBean(LoadBalancerClientFactory.class)
	public XForwardedHeadersTransformer xForwarderHeadersTransformer(
			LoadBalancerClientFactory loadBalancerClientFactory) {
		return new XForwardedHeadersTransformer(loadBalancerClientFactory);
	}
```



# example1
```java
@SpringBootApplication
public class XForwardedHeadersTransformerExampleApplication {

    public static void main(String[] args) {
        ConfigurableApplicationContext context = SpringApplication.run(XForwardedHeadersTransformerExampleApplication.class, args);
        Map<String, XForwardedHeadersTransformer> transformerMap = context.getBeansOfType(XForwardedHeadersTransformer.class);
        System.out.println("transformerMap is Empty: " + CollectionUtils.isEmpty(transformerMap));
    }

}

// console

transformerMap is Empty: true

```


# example2
```java
@SpringBootApplication
public class XForwardedHeadersTransformerExampleApplication {

    public static void main(String[] args) {
        ConfigurableApplicationContext context = SpringApplication.run(XForwardedHeadersTransformerExampleApplication.class, args);
    }


    @Bean
    public org.springframework.cloud.loadbalancer.core.XForwardedHeadersTransformer  xForwarderHeadersTransformer(LoadBalancerClientFactory clientFactory) {
        return new org.springframework.cloud.loadbalancer.core.XForwardedHeadersTransformer(clientFactory);
    }

}

// console
***************************
APPLICATION FAILED TO START
***************************

Description:

The bean 'xForwarderHeadersTransformer', defined in class path resource [org/springframework/cloud/loadbalancer/config/BlockingLoadBalancerClientAutoConfiguration.class], could not be registered. A bean with that name has already been defined in  XForwardedHeadersTransformerExampleApplication and overriding is disabled.

Action:

Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true


```

**Comment by OlgaMaciaszek** [comment]
Ok. you're right. Will bring it back. Sorry for the confusion.

**Comment by galaxy-sea** [comment]
> Ok. you're right. Will bring it back. Sorry for the confusion.

hello @OlgaMaciaszek , Thank you for taking this issue again

**Comment by OlgaMaciaszek** [comment]
Thanks for the fix @galaxy-sea .

**Pull request closed without merging**
