### PR TITLE
Remove URL check that causes loading 401 responses from Spring Cloud …

### PR DESCRIPTION
**Pull request by rgoers**
Log4j 2 provides enhanced Spring Boot and Spring Cloud Config support with its log4j-spring-boot and log4j-spring-cloud-config-client modules. The Spring Cloud Config Client allows Log4j configuration files to be managed in Spring Cloud Config allowing for dynamic updating of the configuration, configurable SSL support, and support for credentials to access Spring Cloud Config server.

Unfortunately, Spring Cloud Commons' PropertySourceBootstrapConfiguration class causes a 401 error response when trying to access a logging configuration file from Spring Cloud Configuration server when credentials are required. This check really provides no value since the underlying LoggingSystem will throw an exception if the url cannot be accessed, and because it does not include credentials it results in a 401 response that prevents the Spring Boot application from starting if credentials are required to access the Spring Cloud Configuration server.

### CODE REVIEW

**Comment by spencergibb** [comment]
We'll follow the conversation in the boot PR

**Comment by rgoers** [comment]
Thanks Spencer. I should note that the check in this piece of code should never fail. By the time this check happens the check in Spring Boot will already have occurred. Obviously if that fails this will never be reached. However, I do understand the desire to keep the logic the same.

**Comment by rgoers** [comment]
The fix for Spring Boot is available in 2.2.10 and 2.3.4.  Please either apply this or modify the affected code to match Spring Boot.

**Comment by rgoers** [comment]
Any updates on this?

**Pull request merged**
