### PR TITLE
Fix HTTP connection leak when a response status code is retryable

### PR DESCRIPTION
**Pull request by JonathanO**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@JonathanO Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-commons&pullRequestId=253)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-commons&pullRequestId=253) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by ryanjbaxter** [comment]
Thanks!  Can you please sign the CLA?

**Comment by JonathanO** [comment]
I'm waiting on legal to get back to me about the CLA, hopefully wont be long.

**Comment by ryanjbaxter** [comment]
OK.  Please let us know if it is going to take some time for that to happen.  I would like to include this fix in the `1.2.x` branch as well and we were looking to do a release of that branch this week.

**Comment by JonathanO** [comment]
If it's not likely to happen by the end of tomorrow, I'll let you know.

**Comment by pivotal-issuemaster** [comment]
@JonathanO Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-commons&pullRequestId=253)!

**Comment by JonathanO** [comment]
Done, sorry for the delay and just going silent, had a family emergency to deal with end of last week.

**Pull request merged**
