### PR TITLE
Make use of a request factory for filter/interceptor

### PR DESCRIPTION
**Pull request by m11r9000**
This PR involves creating a request factory that will be used to convert incoming HTTP requests from ReactorLoadBalancerExchangeFilterFunction/LoadBalancerInterceptor to `org.springframework.cloud.client.loadbalancer.reactive.Request`.

`RequestFactory` has one method that allows developers to plug in their own implementation for doing the conversion `ClientRequest -> Request<?>` or `HttpRequest -> Request<?>` or any other request object for that matter. It also contains default implementations that represents the default strategy of checking the `loadBalancerHint`.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@andaziar Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-commons&pullRequestId=732)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-commons&pullRequestId=732) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@andaziar Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-commons&pullRequestId=732)!

**Comment by spencergibb** [comment]
Thanks, but we've already started work on this in #714

https://github.com/spring-cloud/spring-cloud-commons/pull/714/files#diff-400f286716d58d0e3a20e3b639b706b0R51

**Comment by andersenleo** [comment]
@spencergibb this PR was (is) related to the discussion in #672 -- it's not obvious to me how the referenced PR solved the issue of extracting a `hint` (or a concrete `Request<T>` from a http request (or I'm missing something)?

**Comment by spencergibb** [comment]
The line I linked to has a create request method that can be implemented. Anyway, I think it's too early to consider something like this until #672 is done. I can reopen and put it on hold.

**Comment by andersenleo** [comment]
> The line I linked to has a create request method that can be implemented

Thanks for the quick response. Our purpose was to inject the strategy in the `WebClient/RestTemplate` filter/interceptor. The `createRequest()` in the linked issue seems to be scoped to the LoadBalancer (at which point the http-request context is gone)?

Either way - as mentioned in #672 - we can find a way to work around this in our own code, but it would be much better if our work-around was somewhat aligned to your future design :)

**Comment by spencergibb** [comment]
Sure. We can revisit after #672.

**Comment by spencergibb** [comment]
The build fails BTW
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project spring-cloud-commons: Compilation failure

[ERROR] /home/appuser/project/spring-cloud-commons/src/main/java/org/springframework/cloud/client/loadbalancer/reactive/ReactiveLoadBalancer.java:[49,9] Unexpected @FunctionalInterface annotation

[ERROR]   org.springframework.cloud.client.loadbalancer.reactive.ReactiveLoadBalancer.Factory is not a functional interface

[ERROR]     multiple non-overriding abstract methods found in interface org.springframework.cloud.client.loadbalancer.reactive.ReactiveLoadBalancer.Factory

[ERROR] -> [Help 1]
```

**Comment by andaziar** [comment]
Hi and thank you for the quick replies @spencergibb . I'll fix the compile errors in this PR. Apologies for that. Sloppiness on my end.

And for clarifying regarding intent of this PR; it's a suggestion to showcase how one could extract the loadbalancer hint from the incoming request while also giving developers the power to do so as they see fit e.g. checking a header called `loadBalancerHint` or any other strategy that suits them.

**Comment by OlgaMaciaszek** [comment]
Closing as still marked as work in progress and no recent activity.

**Pull request closed without merging**
