### PR TITLE
create RestTemplate with LoadBalancerInterceptor using @LoadBalanced qua...

### PR DESCRIPTION
**Pull request by spencergibb**
...lifier.

fixes https://github.com/spring-cloud/spring-cloud-netflix/issues/267

@dsyer is this along the lines of what you were thinking?

### CODE REVIEW

**Comment by dsyer** [comment]
I like the `@LoadBalanced`. Where does it get used though? Don't you need to inject it somewhere?

**Comment by spencergibb** [comment]
We don't inject `RestTemplate` anywhere, just make it available to users.  When you want the load balanced `RestTemplate` you do:

```
@Autowired
@LoadBalanced
private RestTemplate loadBalanced;
```

**Comment by dsyer** [comment]
OK, I like. Can we do the same thing with `OAuth2RestTemplate`?

**Comment by spencergibb** [comment]
yup

**Comment by spencergibb** [comment]
in the case of `OAuth2RestTemplate` should we create both one with `@LoadBalanced` and one without?

**Comment by spencergibb** [comment]
https://github.com/spring-cloud/spring-cloud-security/issues/51

**Pull request closed without merging**
