### PR TITLE
fixed Bug with SimpleServiceInstance: getScheme() was not  implemente…

### PR DESCRIPTION
**Pull request by dagerber**
…d and always returned https, even if URI had an http scheme

fixes https://github.com/spring-cloud/spring-cloud-commons/issues/823

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@dagerber Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-commons&pullRequestId=827)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-commons&pullRequestId=827) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@dagerber Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-commons&pullRequestId=827)!

**Comment by dagerber** [comment]
Seems have to be fixed with https://github.com/spring-cloud/spring-cloud-commons/commit/72762d76ed9eccc5876e5bf099c2495c4c44ff3e

**Comment by dagerber** [comment]
Sorry, my fault closing the PR. Problem ist not solved

**Comment by spencergibb** [comment]
Sorry for the delay. If you're up to it, can you rebase and fix the conflicts?

**Comment by dagerber** [comment]
I opened a new pull request, because I merged instead of rebased the old one.
Content is the same, but rebased: https://github.com/spring-cloud/spring-cloud-commons/pull/926

**Pull request closed without merging**
