### PR TITLE
Adds javax.sql.DataSource to refreshables

### PR DESCRIPTION
**Pull request by ileler**
Perfecting the processing method of [gh-318](https://github.com/spring-cloud/spring-cloud-commons/issues/318)

### CODE REVIEW

**Comment by ileler** [comment]
Can you take a look at  https://github.com/spring-cloud/spring-cloud-commons/issues/318#issuecomment-407623361

Most of the time, we use interfaces, not subclasses, so I think 'javax.sql.DataSource' should in the default.

**Comment by spencergibb** [comment]
Please try with boot 2.0.4 and Finchley.SR1

**Comment by ileler** [comment]
I tried it, the problem is still the same, you can look at the [sample code](https://github.com/ileler/java/tree/hikari-exception/hikari-exception) provided in https://github.com/spring-cloud/spring-cloud-commons/issues/318#issuecomment-407623361.

**Comment by spencergibb** [comment]
I can't run that code as I don't have mysql. Care to update it so there are no external dependencies (ie H2 or similar)?

**Comment by ileler** [comment]
I have switched the database from mysql to h2, and the problem still exists. Please take a look.

**Comment by spencergibb** [comment]
Adding the `Datasource` interface does indeed fix the issue, but is still only limited to Hikari. I'd rather not add it if Hikari is not used. Flagging for team discussion.

**Comment by ileler** [comment]
Yes, but Hikari is used by default
😂

**Comment by spencergibb** [comment]
What we're going to try and do is inspect the implementation type of the bean, that way we don't have to add `DataSource` which isn't needed if it is not Hikari.

**Comment by spencergibb** [comment]
After trying to implement this, we are going to add a documentation note, but you should either set `spring.cloud.refresh.extra-refreshable=javax.sql.DataSource` or, more appropriately, strongly type your `DataSource` bean

```java
	@Primary
	@Bean(name = "dbDataSource")
	@ConfigurationProperties(prefix = "datasource.db")
	public HikariDataSource dbDataSource() {
		return DataSourceBuilder.create().type(HikariDataSource.class).build();
	}
```

**Pull request closed without merging**
