### PR TITLE
Use new boot ConfigData framework

### PR DESCRIPTION
**Pull request by spencergibb**
Bootstrap is now opt-in.

See #608 for original motivation.

### CODE REVIEW

**Comment by spencergibb** [comment]
If you review post-merge, not a problem, I can address issues later since this is just a milestone.

**Comment by dzou** [comment]
@spencergibb - Hey we have a library which provides a custom property source for bootstrap configuration when users add our `starter` dependency to their project.

Is bootstrap property sources being deprecated or is there an alternate way to access this feature? We are also wondering if we should instruct users that they should add `spring.config.use-legacy-processing=true` to their `application.properties` now or if we might be able to set the property to true in our starter dependency by default somehow.

**Comment by ruben056** [comment]
Because bootstrapping is now, my client no longer connects to the config server (bootstrap properties with config server uri are no longer read).
Adding: "spring.cloud.bootstrap.enabled=true" to the application.properties does not help. When this property is evaluated (BootstrapApplicationListener.onApplicationEvent), using "Environment.getProperty()", it is always empty...
Same for property "spring.config.use-legacy-processing".
Putting these properties in bootstrap.properties does not make sense because it will not be read, but putting them in application.properties also does not work, what should be done here?
Also I see there is a way of bootstrapping if the  "org.springframework.cloud.bootstrap.marker.Marker" class is present, but it is not in the dependencies I have... (are you supposed to create it yourself?)

What is they new/correct way to have the client now about and connect to the config server after these changes?
I used the spring initializr to create the project with spring boot 2.4.0 (gradle). Only dependency was the "spring could config client", which was version "2020.0.0-M5".

**Comment by ryanjbaxter** [comment]
@ruben056 see the documentation

https://docs.spring.io/spring-cloud-config/docs/3.0.0-M5/reference/html/#config-first-bootstrap

> It must be set as a System Property or environment variable.

**Comment by ruben056** [comment]
@ryanjbaxter Thx for the info, I was looking at the "older" docs I guess (https://cloud.spring.io/spring-cloud-config/multi/multi__spring_cloud_config_client.html)

**Comment by dzou** [comment]
@ruben056 - I think instead of setting the properties you can try using the new `spring-cloud-starter-bootstrap` to enable bootstrap; see: https://github.com/spring-cloud/spring-cloud-release/wiki/Spring-Cloud-2020.0-Release-Notes#breaking-changes

Adding this dependency to your project should have the equivalent effect of using `spring.config.use-legacy-processing`. I think for most applications its not practical to use the system property/environment variable route.

I think the "preferred" style is to migrate to the new `spring.config.import` style that is also discussed in the link. Think this should be in the new docs for config server.

**Pull request merged**
