### PR TITLE
Enforces the order of RoundRobinLoadBalancer when positive overflow

### PR DESCRIPTION
**Pull request by jizhuozhi**

### CODE REVIEW

**Comment by jizhuozhi** [comment]
It also fixes the bug #1074

**Comment by OlgaMaciaszek** [comment]
Fixes gh-1074.

**Review by OlgaMaciaszek — CHANGES_REQUESTED** [review]
Hello, @jizhuozhi - thanks for submitting the PR. In general, it looks good, but some minor changes should be added:
1) Please add your full name and surname with `@author` tag to the javadocs of any modified/ added classes.
2) Could you please submit these changes against `3.1.x` branch instead of `main`? We'll included them in the `2021.x` release train as well then.

**Comment by jizhuozhi** [comment]
> Hello, @jizhuozhi - thanks for submitting the PR. In general, it looks good, but some minor changes should be added:
> 
> 1. Please add your full name and surname with `@author` tag to the javadocs of any modified/ added classes.
> 2. Could you please submit these changes against `3.1.x` branch instead of `main`? We'll included them in the `2021.x` release train as well then.

@OlgaMaciaszek No problem, I will close this and create a new PR. 'Cause I don't now how to change the source branch.

**Comment by OlgaMaciaszek** [comment]
Ok. Please do.

**Pull request closed without merging**
