### PR TITLE
Update SimpleDiscoveryClientAutoConfiguration.java

### PR DESCRIPTION
**Pull request by sosoba**
Fix for hostnames includes backshlash

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@sosoba Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-commons&pullRequestId=798)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-commons&pullRequestId=798) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@sosoba Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-commons&pullRequestId=798)!

**Comment by spencergibb** [comment]
Care to explain the cause?

**Comment by sosoba** [comment]
Unix `hostname` can contain `\` (backshlash) character.
socker-compose.yaml 
```yaml
version: '3'
services:

  springapp:
    hostname: 'ab\cd'
```

Unfortunately `URI.create` (line 71) fail on it. Because you create virtual url is acceptable to replace `\` by `/`.

**Comment by spencergibb** [comment]
We don't support Unix hostnames.

**Comment by sosoba** [comment]
> 
> 
> We don't support Unix hostnames.

You are wrong. This expression: ```java
this.inet.findFirstNonLoopbackHostInfo().getHostname();
```
get hostname. And when it contain backslash Spring fail.

**Pull request closed without merging**
