### PR TITLE
Remove unnecessary sign check, whether positive or negative

### PR DESCRIPTION
**Pull request by jizhuozhi**
The sign bit is ignored, this allows pos to loop sequentially from 0 to Integer.MAX_VALUE.
So there is no need to check whether positive or negative.

### CODE REVIEW

**Comment by jizhuozhi** [comment]
This way we can reduce instruction cycles in any case

**Comment by jizhuozhi** [comment]
@OlgaMaciaszek Hello, PTAL. 
I found there is no need to check the sign of pos, whether positive or negative. And the extra checks come with more overhead.

**Comment by jizhuozhi** [comment]
Just like the same code written in C, and compiled with `gcc` and `gcc -O3`.

**Review by OlgaMaciaszek — APPROVED** [review]
Thanks for submitting the PR @jizhuozhi. LGTM.

**Pull request merged**
