### PR TITLE
fix double checked locking with volatile

### PR DESCRIPTION
**Pull request by shenjianeng**
double checked locking with volatile

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@shenjianeng Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-commons&pullRequestId=649)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-commons&pullRequestId=649) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@shenjianeng Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-commons&pullRequestId=649)!

**Comment by spencergibb** [comment]
Can you please explain the problem you're having and why this corrects it?

**Comment by shenjianeng** [comment]
sorry, my English is poor。
> references:https://stackoverflow.com/questions/7855700/why-is-volatile-used-in-double-checked-locking
> The real problem is that Thread A may assign a memory space for instance before it is finished constructing instance. Thread B will see that assignment and try to use it. This results in Thread B failing because it is using a partially constructed version of instance.

**Comment by spencergibb** [comment]
I understand the use of volatile. What problem are you seeing in spring cloud commons that prompted the change?

**Comment by shenjianeng** [comment]
not yet but for preventing potential problems

>`org.springframework.cloud.context.scope.GenericScope.BeanLifecycleWrapper#getBean`
> double checked locking without volatile.

**Comment by f4cklangzi** [comment]
If you don't add volatile, there may be deadlocks in getBean. I encountered

**Pull request merged**
