### PR TITLE
Fixes failing maven eclipse:eclipse goal.

### PR DESCRIPTION
**Pull request by fahimfarookme**
The `./mvnw eclipse:eclipse` goal fails with the following error;

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-eclipse-plugin:2.10:eclipse (default-cli) on project spring-cloud-test-support: Unable to resolve resource location: spring-cloud-commons-pr/eclipse/org.eclipse.jdt.ui.prefs -> [Help 1]
```

The `eclipse` directory does not exist. Also the location of the project root directory is resolved with `main.basedir` property defined in child poms. However maven 3.3.1 introduces `maven.multiModuleProjectDirectory` which points to the project root directory, hence `main.basedir` is unnecessary.

As a fix, added the `eclipse` directory (copied from spring-cloud-netflix) and used `maven.multiModuleProjectDirectory` in place of `main.basedir`.

### CODE REVIEW

**Comment by ryanjbaxter** [comment]
Where did you get the files in `/eclipse`?

**Comment by fahimfarookme** [comment]
It's from [spring-cloud-netflix/eclipse](https://github.com/spring-cloud/spring-cloud-netflix/tree/master/eclipse)

**Comment by ryanjbaxter** [comment]
@fahimfarookme we had to add `main.basedir` back because it was causing issues with your documentation builder.

https://github.com/spring-cloud/spring-cloud-commons/commit/c65f306f4ebef10cbc28d5b2f8d2257258426dd6#diff-48fabae9c2e321b2ab4d99057d5dc32eR18

**Comment by fahimfarookme** [comment]
@ryanjbaxter a better solution would be to use `${maven.multiModuleProjectDirectory}` in spring-cloud-build [here](https://github.com/spring-cloud/spring-cloud-build/blob/master/pom.xml#L847)

**Comment by spencergibb** [comment]
Since this isn't a feature, but a tool config, let's leave it alone until 2.0 goes GA, then we can revisit

**Pull request merged**
