### PR TITLE
Fix "Service Registry Actuator Endpoint URL" in doc is wrong(#1240)

### LINKED ISSUE #1240: "Service Registry Actuator Endpoint URL" in doc is wrong
**Describe the bug**
The "Service Registry Actuator Endpoint URL" described in [doc](https://docs.spring.io/spring-cloud-commons/docs/current/reference/html/#service-registry-actuator-endpoint) is out-of-dated.

After the [PR](https://github.com/spring-cloud/spring-cloud-commons/pull/701) has been merged, the The "Service Registry Actuator Endpoint URL" should be `serviceregistry` instead of `service-registry`.

**Sample**
image

image

### PR DESCRIPTION
**Pull request by Pengfei-Lu**
Fix #1240

### CODE REVIEW

**Comment by Pengfei-Lu** [comment]
Any update about this?

**Comment by Pengfei-Lu** [comment]
Any update about this? @spencergibb

**Comment by Pengfei-Lu** [comment]
I've fix the conflicts with the main branch. Please check. @spencergibb

**Review by OlgaMaciaszek — APPROVED** [review]
Thanks @Pengfei-Lu. LGTM.

**Pull request merged**
