### PR TITLE
Add support for looking up services by metadata in DiscoveryClient

### PR DESCRIPTION
**Pull request by darylrobbins**
Added a new getInstances() method to DiscoveryClient, which also accepts metadata. This can be used, for example, to lookup a service with a given tag in Consul. Also added AbstractDiscoveryClient to minimize the impact of future enhancements to DiscoveryClient, so that all implementation will no longer need to be updated.

This change will require corresponding changes to all the existing implementations.

### CODE REVIEW

**Comment by spencergibb** [comment]
Debating this one. You could just inject `ConsulDiscoveryClient` that has a method to query by metadata.

**Comment by darylrobbins** [comment]
How about a `MetadataAwareDiscoveryClient`?

**Comment by darylrobbins** [comment]
I figured this was likely to be somewhat contentious, but I really need mainstream support for this functionality to make it at all viable.

**Comment by spencergibb** [comment]
Definitely don't want to force the change to other clients when they won't support it. What's the difference between a new interface here and using the consul implementation directly?

**Comment by darylrobbins** [comment]
I was hoping to refer to this interface in ribbon. This would also allow adding support for other discovery providers that support some kind of metadata-based search.

**Comment by spencergibb** [comment]
Each `DiscoveryClient` impl also as a Ribbon `ServerList` implementation.

**Comment by spencergibb** [comment]
Closing in favor of #572

**Pull request closed without merging**
