### PR TITLE
Move @ConditionalOnRefreshScope from spring-cloud-netflix

### PR DESCRIPTION
**Pull request by brenuart**
This PR addresses issue https://github.com/spring-cloud/spring-cloud-commons/issues/411.

The first commit is a copy of the original the conditional classes from spring-cloud-netflix.
The second commit makes the conditions simpler due to the fact that they now belong to the same project/dependency as the `RefreshScope` class itself.
I made two distinct commits on purpose to highlight the changes and help reviewers determine if the proposed changes are acceptable or not.

### CODE REVIEW

**Comment by spencergibb** [comment]
Why did you remove this part
```
@ConditionalOnMissingClass("org.springframework.cloud.context.scope.refresh.RefreshScope")
```
I'd think not having the class would be fine too.

**Comment by spencergibb** [comment]
I guess we need to verify that s-c-netflix is indeed depedent on spring-cloud-context

**Comment by spencergibb** [comment]
spring-cloud-netflix-eureka-client depends on spring-cloud-netflix-core which has spring-cloud-context as optional, though spring-cloud-starter-netflix-eureka-client includes spring-cloud-starter. Using this in spring-cloud-netflix-eureka-client will make this required

**Comment by brenuart** [comment]
@spencergibb Oh, I see... using this condition instead of the one currently in spring-cloud-netflix-eureka-client would make the dependency on spring-cloud-context required. Is that what you mean?
Does it mean using `@ConditionalOnRefreshScope` would not work and would instead throw an exception at runtime if spring-cloud-context is not on the classpath?

If so, it is likely to be the case for any other similar use case... which makes the PR less useful I'm afraid :(

The idea behind this move into commons was to have the condition defined closer to where the feature lives and maintained by the guys who actually wrote it. I always feel uncomfortable when writing such conditions myself as I may not be aware of every ins and outs. See what I mean?

Can't we find another option ?

**Comment by spencergibb** [comment]
I think the sentiment was right, but by virtue of having `@ConditionalOnRefreshScope` from spring-cloud-context, you'd also have `@RefreshScope`.

**Pull request closed without merging**
