### PR TITLE
Remove duplicate code in BlockingLoadBalancerClient

### PR DESCRIPTION
**Pull request by Johnny850807**
Remove duplicate code in BlockingLoadBalancerClient 😄

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@Johnny850807 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-commons&pullRequestId=869)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-commons&pullRequestId=869) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@Johnny850807 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-commons&pullRequestId=869)!

**Review by OlgaMaciaszek — COMMENTED** [review]
@Johnny850807 Thanks for submitting the PR. LGTM. Could you merge changes from `origin/master` to resolve the conflict? Will merge it straight away then.

**Comment by OlgaMaciaszek** [comment]
Will cherry-pick to avoid conflicts.

**Comment by OlgaMaciaszek** [comment]
Merged within https://github.com/spring-cloud/spring-cloud-commons/commit/361a8c2baefd3f580cd11feb38337e8ea49e476a.

**Comment by Johnny850807** [comment]
Oops, I missed it, thank you very much.

**Pull request closed without merging**
