### PR TITLE
changed class visibility

### LINKED ISSUE #973: Switch remaining jUnit 4 tests to jUnit jupiter

### PR DESCRIPTION
**Pull request by ManasviGoyal**
fixes #973

### CODE REVIEW

**Comment by ManasviGoyal** [comment]
hi.pls check. @OlgaMaciaszek 
i tried to update every file but might have missed as there were many.
what might be the reason for error?

**Comment by spencergibb** [comment]
Java compile failed because we reference tests in a test suite. Did you run a build locally?

**Comment by ManasviGoyal** [comment]
> Java compile failed because we reference tests in a test suite. Did you run a build locally?



> Java compile failed because we reference tests in a test suite. Did you run a build locally?

no. how can i do that?

**Comment by OlgaMaciaszek** [comment]
@ManasviGoyal will explain in DM.

**Pull request closed without merging**
