### PR TITLE
Introduce property spring.cloud.bootstrap.additional-location according to spring.config.additional-location (#466)

### LINKED ISSUE #466: Different behavior of spring.cloud.bootstrap.location since Spring Boot 2
I noticed a different behavior of the property `spring.cloud.bootstrap.location` since Spring Boot 2.x

**Behavior in Spring Boot 1.x:**

- Build in bootstrap.properties file inside the JAR *is* regarded
- Specified bootstrap.properties file is regarded

**Behavior in Spring Boot 2.x:**

- Build in bootstrap.properties file inside the JAR *is not* regarded
- Specified bootstrap.properties file is regarded

Reason is that since Spring Boot 2 the behavior of the `spring.config.location configuration` has been fixed and the property `spring.cloud.bootstrap.location` works now also as desired.

See https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide#configuration-location

I restored the origin behavior by adding the default search locations to the property in addition `spring.cloud.bootstrap.location=classpath:/,classpath:/config/,file:./,file:./config/,file:/my/special/search/location`

It would be great to introduce also a new property `spring.cloud.bootstrap.additional-location` like the `spring.config.additional-location`.

See also https://stackoverflow.com/questions/54204333/different-behavior-of-spring-cloud-bootstrap-location-since-spring-boot-2

I'll try to provide a pull-request in the next days for that.

### PR DESCRIPTION
**Pull request by srempfer**
fixes #466

### CODE REVIEW

**Comment by srempfer** [comment]
Sure. Is this enough or is there an additional location?

**Comment by ryanjbaxter** [comment]
I think you should describe how the new property is different than the existing property.  Also could you submit this against the 2.0.x branch?

**Comment by aantono** [comment]
Is there an update on this PR?  Looks like it's been ready to merge since January, and it's a needed feature!

**Comment by aantono** [comment]
@srempfer Can this be looked at and merged if good, this is quite a needed feature, so would be appreciated to have it in the release!

**Comment by srempfer** [comment]
@ryanjbaxter Is there still something missing? Could I do something so that this pull-request could be merged?

**Comment by ryanjbaxter** [comment]
@srempfer sorry for the delay....could you rebase this on the 2.1.x stream?

**Pull request merged**
