### PR TITLE
Fix bug of service instance refetching when repeating health check is activated

### PR DESCRIPTION
**Pull request by rchigvintsev**
Fixes gh-899

I'm not sure it is a proper solution to this issue but it works.

### CODE REVIEW

**Comment by OlgaMaciaszek** [comment]
Fixes gh-899.

**Review by OlgaMaciaszek — COMMENTED** [review]
@rchigvintsev Thanks for submitting the PR. This, in fact, fixes the issue. However, since the issue is present in `Hoxton` release train as well, could you please submit it against the `2.2.x` branch instead of `master` so that the change is included in both release trains. Also, please add your full name with `@author` tag to the javadocs in the classes you've modified.

**Review by OlgaMaciaszek — CHANGES_REQUESTED** [review]
Changes reqeusted in another comment.

**Comment by rchigvintsev** [comment]
@OlgaMaciaszek I've just created a new [PR](https://github.com/spring-cloud/spring-cloud-commons/pull/904) against 2.2.x branch.

**Comment by OlgaMaciaszek** [comment]
@rchigvintsev Thanks :)

**Comment by OlgaMaciaszek** [comment]
Closing in favour of gh-904.

**Pull request closed without merging**
