### PR TITLE
Add retryable status code check

### PR DESCRIPTION
**Pull request by ryanjbaxter**
Part of the fix to address spring-cloud/spring-cloud-netflix#1540

### CODE REVIEW

**Comment by ryanjbaxter** [comment]
Is this OK to merge back to 1.1.x?  It is an interface change, so could possibly break some folks...

**Comment by spencergibb** [comment]
I hesitate to introduce a breaking change in a SR.

**Comment by ryanjbaxter** [comment]
So should we just make this feature available in Dalston then?  I am fine with that

**Comment by spencergibb** [comment]
I think so

**Pull request merged**
